# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChargingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5fae\u4fe1unionid')),
                ('open_id', models.CharField(default='', max_length=100, verbose_name='\u5fae\u4fe1openid')),
                ('order_id', models.CharField(default='', max_length=30, verbose_name='\u8ba2\u5355id')),
                ('charge_num', models.IntegerField(default=0, verbose_name='\u5145\u503c\u91d1\u989d')),
                ('order_status', models.IntegerField(default=0, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5145\u503c\u8ba2\u5355\u8868',
                'verbose_name_plural': '\u7528\u6237\u5145\u503c\u8ba2\u5355\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5fae\u4fe1unionid')),
                ('open_id', models.CharField(default='', max_length=100, verbose_name='\u5fae\u4fe1openid')),
                ('vip_level', models.IntegerField(default=0, verbose_name='vip\u7b49\u7ea7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f\u8868',
            },
        ),
    ]
