# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchargingorder',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
    ]
