# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdem', '0003_userchargingorderbak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchargingorder',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6635\u79f0'),
        ),
        migrations.AddField(
            model_name='userchargingorderbak',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6635\u79f0'),
        ),
    ]
