# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdem', '0004_auto_20180202_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchargingorder',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
